[package]
name = "mailer"
version = "0.1.0"
authors = ["Vid Kavšek <vkavsek@gmail.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "mailer"
path = "src/main.rs"

[dependencies]
# AWS Lambda 
lambda_http = "0.11"
axum-aws-lambda = "0.7"
# Async
tokio = { version = "1", features = ["full"] }
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["trace", "request-id"] }
# async-trait = "0.1"
# Tracing
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "3.7"
# Config 
config = "0.14"
# Time 
chrono = { version = "0.4", default-features = false, features = ["clock"] }
# Others
secrecy = { version = "0.8", features = ["serde"] }
uuid = { version = "1.8", features = ["v4"] }
strum_macros = "0.26"
derive_more = "0.99"

# SQL 
[dependencies.sqlx]
version = "0.7"
default-features = false
features = ["runtime-tokio-rustls", "macros", "postgres", "chrono", "migrate"]

[dev-dependencies]
anyhow = "1"
reqwest = { version = "0.12", features = ["json"] }
