[package]
name = "mailer"
version = "0.1.0"
authors = ["Vid Kavšek <vkavsek@gmail.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "mailer"
path = "src/main.rs"

[dependencies]
# Async
tokio = { version = "1", features = ["full"] }
axum = "0.7"
# async-trait = "0.1"
# Tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
# Error 
thiserror = "1"
# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
anyhow = "1"
reqwest = { version = "0.11", features = ["json"] }
serial_test = "3"
