[package]
name = "mailer"
version = "0.1.0"
authors = ["Vid Kavšek <vkavsek@gmail.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "mailer"
path = "src/main.rs"

[dependencies]
# Async
tokio = { version = "1", features = ["full"] }
axum = "0.7"
# async-trait = "0.1"
# Tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
# Error 
thiserror = "1"
# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
# Config 
config = "0.14"
# Time 
chrono = { version = "0.4", default-features = false, features = ["clock"] }
# Others
uuid = { version = "1.8", features = ["v4"] }

# SQL 
[dependencies.sqlx]
version = "0.7"
default-features = false
features = ["runtime-tokio-rustls", "macros", "postgres", "chrono", "migrate"]

[dev-dependencies]
anyhow = "1"
reqwest = { version = "0.11", features = ["json"] }
serial_test = "3"
