# #[derive(Deserialize)]
# pub struct AppConfig {
#     pub db_config: DatabaseConfig,
#     pub app_port: u16,
# }
#
# #[derive(Deserialize)]
# pub struct DatabaseConfig {
#     pub username: String,
#     pub password: String,
#     pub port: u16,
#     pub host: String,
#     pub db_name: String,
# }

app_port = 8000

[db_config]
host = "127.0.0.1"
port = 5432
username = "postgres"
password = "password"
db_name = "newsletter"
